name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**' 

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: Checkout target repository
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate merging

      # Step 2: Set up Git configuration
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # Step 3: Add upstream repository and fetch changes
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/hamster1963/nezha-dash.git
          git fetch upstream

      # Step 4: Merge changes from upstream excluding workflow files
      - name: Merge upstream changes excluding workflow files
        shell: bash
        run: |
          # Merge upstream/main into current branch without committing
          git merge upstream/main --no-commit --no-ff || true

          # Remove workflow files from the staged changes
          git reset HEAD .github/workflows/ || true

          # Restore the workflow files to their original state
          git checkout -- .github/workflows/ || true

          # Check if there are changes to commit
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Merge upstream changes"

            # Push changes to the target branch
            git push origin main
          fi

      # Step 5: Handle errors
      - name: Sync check
        if: failure()
        run: |
          echo "[Error] An error occurred during the sync process."
          exit 1
